export const ui = {
    'authority': {
        'en': 'Do we have the authority to bid/contract for the item or service?',
        'es': '¿Tenemos autoridad para licitar/contratar el artículo o servicio?',
        'ko': '저희에게 해당 품목 또는 서비스에 대한 입찰/계약 권한이 있습니까?',
        'zh': '我们是否有权对该物品或服务进行投标/签订合同？',
    },
    'public': {
        'en': 'Is it solicited by a public or non-profit agency? City, County, State,School District, Port, non-profit, or Co-Op established for this purpose?',
        'es': '¿La solicitud proviene de una agencia pública o sin fines de lucro? ¿Ciudad, condado, estado, distrito escolar, puerto, organización sin fines de lucro o cooperativa establecida para este fin?',
        'ko': '공공기관 또는 비영리기관에서 요청한 것입니까? 시, 군, 주, 교육구, 항만, 비영리단체 또는 이 목적을 위해 설립된 협동조합에서 요청한 것입니까?',
        'zh': '是否由公共机构或非营利机构征集？例如，市、县、州、学区、港口、非营利组织或为此目的设立的合作社？',
    },
    'consistent': {
        'en': 'Was the solicitation conducted and awarded using a process consistent to HCPSS Procurement Policies?',
        'es': '¿La licitación y la adjudicación se realizaron mediante un proceso acorde con las políticas de adquisiciones de HCPSS?',
        'ko': '입찰 및 계약 체결 절차가 HCPSS 조달 정책에 부합하는 방식으로 진행되었습니까?',
        'zh': '本次招标和授标流程是否符合HCPSS采购政策？',
    },
    'consistent.help': {
        'en': 'Does this meet our solicitation requirement for quotes or sealed process? Check what our dollar threshold process requires.',
        'es': '¿Cumple esto con nuestros requisitos de solicitud de cotizaciones o proceso sellado? Verifique qué exige nuestro proceso de umbral monetario.',
        'ko': '이 견적서 또는 밀봉 입찰 절차에 대한 당사의 요구 사항을 충족합니까? 당사의 최소 입찰 금액 기준을 확인하십시오.',
        'zh': '这是否符合我们的报价或密封流程招标要求？请查看我们的金额门槛流程要求。',
    },
    'language': {
        'en': 'Does the solicitation and/or contract contain the language to piggyback?',
        'es': '¿La solicitud y/o el contrato contienen la cláusula para la contratación conjunta?',
        'ko': '입찰 공고 및/또는 계약서에 동승 조항을 포함하는 내용이 있습니까?',
        'zh': '招标文件和/或合同中是否包含搭便车条款？',
    },
    'icpa': {
        'en': 'Verify the ICPA solicitation was competitively bid and publicly advertised.',
        'es': 'Verifique que la licitación de la ICPA se haya realizado mediante concurso público y se haya anunciado públicamente.',
        'ko': 'ICPA 입찰이 경쟁 입찰 방식으로 진행되었고 공개적으로 공고되었는지 확인하십시오.',
        'zh': '核实ICPA的招标是否经过公开招标和竞争性投标。',
    },
    'rfp_ifp': {
        'en': 'Was the contract awarded consistent with the RFP/IFB instructions?',
        'es': '¿El contrato se adjudicó de acuerdo con las instrucciones de la solicitud de propuestas/licitación?',
        'ko': '계약 체결은 제안요청서/입찰 제안서 제출 지침에 따라 이루어졌습니까?',
        'zh': '授予的合同是否符合招标书/投标书的要求？',
    },
    'rfp_ifp.help': {
        'en': 'Review the bid tabs or evaluation summary and award recommendations.',
        'es': 'Revise las pestañas de la oferta o el resumen de la evaluación y las recomendaciones de adjudicación.',
        'ko': '입찰 제안서 또는 평가 요약 및 낙찰 추천서를 검토하십시오.',
        'zh': '查看投标标签或评估摘要和授标建议。',
    },
    'agreedToAllow': {
        'en': 'Has the awarded vendor agreed to allow piggybacks? May be included in the contract, may be referenced back to the solicitation document.',
        'es': '¿El proveedor adjudicatario ha aceptado permitir la subcontratación? Puede estar incluido en el contrato o puede hacer referencia al documento de licitación.',
        'ko': '낙찰된 업체가 추가 입찰(piggyback)을 허용하기로 동의했습니까? 계약서에 명시되어 있을 수도 있고, 입찰 공고 문서에 참조되어 있을 수도 있습니다.',
        'zh': '中标供应商是否同意允许搭售？这可能包含在合同中，也可能在招标文件中有所提及。',
    },
    'inEffect': {
        'en': 'Is the solicitation/contract still in effect? If it has renewals, do we have a copy of the valid renewal agreement?',
        'es': '¿Sigue vigente la licitación/contrato? Si incluye cláusulas de renovación, ¿contamos con una copia del acuerdo de renovación vigente?',
        'ko': '입찰/계약이 아직 유효한가요? 갱신 조항이 있다면, 유효한 갱신 계약서 사본을 가지고 계신가요?',
        'zh': '该招标/合同是否仍然有效？如果包含续约条款，我们是否有有效的续约协议副本？',
    },
    'deparment': {
        'en': 'Check the State and Federal debarment list. Is the vendor listed? Have we obtain originating agency\'s competitive procurement documentation?',
        'es': 'Consulte la lista de inhabilitaciones estatales y federales. ¿Aparece el proveedor en la lista? ¿Hemos obtenido la documentación de contratación pública competitiva de la agencia solicitante?',
        'ko': '주 및 연방 정부의 거래 금지 목록을 확인하십시오. 해당 업체가 목록에 있습니까? 해당 기관의 경쟁 입찰 관련 서류를 확보했습니까?',
        'zh': '请查看州和联邦的禁售名单。该供应商是否在名单上？我们是否已获得发起机构的竞争性采购文件？',
    },
    'deparment.help': {
        'en': 'Including public advertisements and proposal evaluations',
        'es': 'Incluyendo anuncios públicos y evaluaciones de propuestas.',
        'ko': '공개 광고 및 제안서 평가를 포함합니다.',
        'zh': '包括公开广告和方案评估',
    },
    'reviewed': {
        'en': 'I have reviewed the items on the above checklist for this solicitation and',
        'es': 'He revisado los elementos de la lista de verificación anterior para esta solicitud y',
        'ko': '저는 위 체크리스트에 있는 항목들을 검토했으며,',
        'zh': '我已审阅上述清单中的各项内容，以了解本次招标的各项要求。',
    },
    'reviewed.meets': {
        'en': 'meets the requirements',
        'es': 'cumple con los requisitos',
        'ko': '요구 사항을 충족합니다',
        'zh': '符合要求',
    },
    'reviewed.notmeets': {
        'en': 'does not meet the requirements',
        'es': 'no cumple con los requisitos',
        'ko': '요구 사항을 충족하지 않습니다',
        'zh': '不符合要求',
    },
    'requestor': {
        'en': 'Requestor',
        'es': 'Solicitante',
        'ko': '요청자',
        'zh': '请求者',
    },
    'date': {
        'en': 'Date',
        'es': 'Fecha',
        'ko': '날짜',
        'zh': '日期',
    },
    'procurement.specialist': {
        'en': 'Procurement Specialist',
        'es': 'Especialista en adquisiciones',
        'ko': '구매 전문가',
        'zh': '采购专员',
    },
    'solicitation.title': {
        'en': 'Solicitation Title',
        'es': 'Título de la solicitud',
        'ko': '공모 제목',
        'zh': '招标标题',
    },
    'meets.requirements': {
        'en': 'Does the Solicitation Meet the Following Requirements?',
        'es': '¿Cumple la solicitud con los siguientes requisitos?',
        'ko': '본 입찰 공고는 다음 요건을 충족합니까?',
        'zh': '该招标是否符合以下要求？',
    },
    'step1': {
        'en': 'STEP 1-To be Completed by the Requestor',
        'es': 'PASO 1 - Debe ser completado por el solicitante',
        'ko': '1단계 - 요청자 작성',
        'zh': '第一步——由申请人填写',
    },
    'requesting.office': {
        'en': 'Requesting Office',
        'es': 'Oficina solicitante',
        'ko': '요청 부서',
        'zh': '请求办公室',
    },
    'contact.name': {
        'en': 'Contact Name',
        'es': 'Nombre de contacto',
        'ko': '연락처 이름',
        'zh': '联系人姓名',
    },
    'phone': {
        'en': 'Phone',
        'es': 'Teléfono',
        'ko': '핸드폰',
        'zh': '电话',
    },
    'vendor.name': {
        'en': 'Vendor Name',
        'es': 'Nombre del proveedor',
        'ko': '벤더명',
        'zh': '供应商名称',
    },
    'procurement.method': {
        'en': 'Procurement Method',
        'es': 'Método de adquisición',
        'ko': '조달 방식',
        'zh': '采购方式',
    },
    'contract.term': {
        'en': 'Contract Term',
        'es': 'Duración del contrato',
        'ko': '계약 기간',
        'zh': '合同期限',
    },
    'available.options': {
        'en': 'Available Options',
        'es': 'Opciones disponibles',
        'ko': '사용 가능한 옵션',
        'zh': '可用选项',
    },
    'purchase.description': {
        'en': 'Purchase Description',
        'es': 'Descripción de la compra',
        'ko': '구매 설명',
        'zh': '购买说明',
    },
    'econ.justification': {
        'en': 'Economic Justification',
        'es': 'Justificación económica',
        'ko': '경제적 타당성',
        'zh': '经济合理性',
    },
    'econ.justification.help': {
        'en': 'A cooperative review request from a program must inctude s verifiable economic justification to why using a cooperative purchasing agreement is more cost effective or likely to realize savings than conducting a sollcitation.',
        'es': 'Una solicitud de revisión cooperativa de un programa debe incluir una justificación económica verificable de por qué el uso de un acuerdo de compra cooperativa es más rentable o tiene más probabilidades de generar ahorros que realizar una solicitud de propuestas.',
        'ko': '프로그램에서 협력 구매 계약을 검토해 달라는 요청에는 협력 구매 계약을 사용하는 것이 입찰을 진행하는 것보다 비용 효율적이거나 절감 효과를 가져올 가능성이 더 높다는 것을 입증할 수 있는 경제적 근거가 포함되어야 합니다.',
        'zh': '项目提出的合作审查请求必须包含可验证的经济理由，说明为什么使用合作采购协议比进行招标更具成本效益或更有可能实现节约。',
    },
    'step2': {
        'en': 'STEP 2-To be Completed by the Procurement Specialist',
        'es': 'PASO 2: Debe ser completado por el especialista en adquisiciones.',
        'ko': '2단계 - 구매 담당자 작성',
        'zh': '步骤二：由采购专员完成',
    },
    'adv_90_days': {
        'en': 'Was the solicitation advertised to the public preceding the date of bid or proposal opening for no less than 5 days and no more than 90 days?',
        'es': '¿Se publicó la convocatoria al público con una antelación no inferior a 5 días ni superior a 90 días a la fecha de apertura de las ofertas o propuestas?',
        'ko': '입찰 또는 제안서 개시일 이전에 최소 5일, 최대 90일 동안 해당 공고가 일반에 공개되었습니까?',
        'zh': '招标公告是否在投标或提案开标日期前至少5天但不超过90天向公众发布？',
    },
    'des_time_place': {
        'en': 'Were sealed bids or proposals opened at a designated time and place?',
        'es': '¿Se abrieron las ofertas o propuestas selladas en un lugar y hora determinados?',
        'ko': '밀봉된 입찰서 또는 제안서는 지정된 시간과 장소에서 개봉되었습니까?',
        'zh': '密封投标书或方案是否在指定时间和地点开启？',
    },
    'witness': {
        'en': 'Was there a witness to the opening?',
        'es': '¿Hubo algún testigo de la inauguración?',
        'ko': '개장 장면을 목격한 사람이 있었나요?',
        'zh': '开幕式有目击者吗？',
    },
    'ifb_names_recorded': {
        'en': '(IFB ONLY) Were the names of bidders and amount of their bids recorded?',
        'es': '(SOLO PARA IFB) ¿Se registraron los nombres de los licitadores y el monto de sus ofertas?',
        'ko': '(IFB에만 해당) 입찰자 이름과 입찰 금액이 기록되었습니까?',
        'zh': '（仅限IFB）是否记录了投标人的姓名和投标金额？',
    },
    'ifb_names_communicated': {
        'en': '(IFB ONLY) Were the names of the bidders and the amount of their bids communicated or made available to the public in some manner?',
        'es': '(SOLO PARA IFB) ¿Se comunicaron o se pusieron a disposición del público de alguna manera los nombres de los licitadores y el monto de sus ofertas?',
        'ko': '(IFB에만 해당) 입찰자의 이름과 입찰 금액이 어떤 방식으로든 공개되었거나 대중에게 알려졌습니까?',
        'zh': '（仅限IFB）投标人的姓名和投标金额是否以某种方式向公众公布或公开？',
    },
    'ifb_responsive': {
        'en': '(IFB ONLY) Was the award made to the responsive and responsible bidder who has submitted the lowest bid that met the requirements and criteria set forth in the bid?',
        'es': '(SOLO IFB) ¿Se adjudicó el contrato al licitador que respondió de manera adecuada y fue responsable, y que presentó la oferta más baja que cumplía con los requisitos y criterios establecidos en la licitación?',
        'ko': '(IFB에만 해당) 입찰서에 명시된 요건과 기준을 충족하는 최저 입찰가를 제출한 적격하고 책임감 있는 입찰자에게 낙찰되었습니까?',
        'zh': '（仅限 IFB）是否将合同授予了符合招标要求和标准的、提交最低报价的响应型且负责任的投标人？',
    },
    'rfp_evaluated': {
        'en': '(RFP ONLY) Were all proposals evaluated based on established Evaluation and Selection Criteria set forth in the solicitation?',
        'es': '(SOLO PARA LA SOLICITUD DE PROPUESTAS) ¿Se evaluaron todas las propuestas en función de los criterios de evaluación y selección establecidos en la solicitud?',
        'ko': '(제안요청서에만 해당) 모든 제안서는 제안요청서에 명시된 평가 및 선정 기준에 따라 평가되었습니까?',
        'zh': '（仅限 RFP）所有提案是否均按照招标文件中规定的既定评估和选择标准进行评估？',
    },
    'rfb_protests': {
        'en': '(RFP ONLY) Were protests allowed as part of the process?',
        'es': '(SOLO PARA LA SOLICITUD DE PROPUESTAS) ¿Se permitieron las protestas como parte del proceso?',
        'ko': '(제안요청서에만 해당) 심사 과정에서 이의 제기가 허용되었습니까?',
        'zh': '（仅限征求建议书）过程中是否允许抗议？',
    },
    'both_secure': {
        'en': '(Both) If the solicitation was sealed, were all bids/proposals kept secure and unopened until the date and time specified in the solicitation?',
        'es': '(Ambos) Si la solicitud era sellada, ¿se mantuvieron todas las ofertas/propuestas seguras y sin abrir hasta la fecha y hora especificadas en la solicitud?',
        'ko': '(두 질문 모두) 입찰 공고가 밀봉된 경우, 모든 입찰서/제안서는 입찰 공고에 명시된 날짜와 시간까지 안전하게 보관되고 개봉되지 않았습니까?',
        'zh': '（两者）如果招标是密封的，所有投标/提案是否都安全保存，直到招标中规定的日期和时间才被打开？',
    },
    'step3': {
        'en': 'Step 3 - To be Completed the Director of Procurement and Materials Management',
        'es': 'Paso 3 - Debe ser completado por el Director de Adquisiciones y Gestión de Materiales.',
        'ko': '3단계 - 구매 및 자재 관리 담당 이사가 완료해야 할 사항',
        'zh': '步骤 3 - 由采购和物料管理总监填写',
    },
    'outcome': {
        'en': 'Outcome',
        'es': 'Resultado',
        'ko': '결과',
        'zh': '结果',
    },
    'approved': {
        'en': 'Approved: The cooperative procurement agreement referenced above has been determined to substantially meet the requirements of Maryland procurement law.',
        'es': 'Aprobado: Se ha determinado que el acuerdo de contratación cooperativa mencionado anteriormente cumple sustancialmente con los requisitos de la ley de contratación pública de Maryland.',
        'ko': '승인됨: 상기 협력 구매 계약은 메릴랜드 주 구매법의 요건을 실질적으로 충족하는 것으로 판단되었습니다.',
        'zh': '已批准：上述合作采购协议经认定基本符合马里兰州采购法的要求。',
    },
    'denied': {
        'en': 'Denied: The cooperative procurement agreement referenced above has been determined not to substantially meet the requirements of Maryland procurement law.',
        'es': 'Denegado: Se ha determinado que el acuerdo de contratación cooperativa mencionado anteriormente no cumple sustancialmente con los requisitos de la ley de contratación pública de Maryland.',
        'ko': '거부됨: 위에 언급된 공동 구매 계약은 메릴랜드 주 구매법의 요건을 실질적으로 충족하지 못하는 것으로 판단되었습니다.',
        'zh': '驳回：经认定，上述合作采购协议不符合马里兰州采购法的实质性要求。',
    },
    'additional': {
        'en': 'Additional justification, if any',
        'es': 'Justificación adicional, si la hubiera.',
        'ko': '추가적인 근거(있을 경우)',
        'zh': '如有其他理由，请说明。',
    },
    'director': {
        'en': 'Director of Procurement and Materials Management',
        'es': 'Director de Adquisiciones y Gestión de Materiales',
        'ko': '구매 및 자재 관리 담당 이사',
        'zh': '采购和物料管理总监',
    },
    'coop.procurement': {
        'en': 'Cooperative Procurement Agency/Organization',
        'es': 'Agencia/Organización de Adquisiciones Cooperativas',
        'ko': '협력조달기관/조직',
        'zh': '合作采购机构/组织',
    },
    'email': {
        'en': 'Email',
        'es': 'Correo electrónico',
        'ko': '이메일',
        'zh': '电子邮件',
    },
    'economic.justification': {
        'en': 'Economic Justification',
        'es': 'Justificación Económica',
        'ko': '경제적 근거',
        'zh': '经济合理性',
    },
    'economic.justification.help': {
        'en': 'A cooperative review request from a program must include a verifiable economic justification to why using a cooperative purchasing agreement is more cost effective or likely to realize savings than conducting a solicitation.',
        'es': 'Una solicitud de revisión cooperativa de un programa debe incluir una justificación económica verificable para explicar por qué utilizar un acuerdo de contratación cooperativa es más eficiente o probable de generar ahorros que realizar una solicitud.',
        'ko': '프로그램에서 협력조달 검토 요청은 협력조달 계약을 사용하는 것이 손해보험료 절감 또는 경쟁을 유도하는 것보다 효율적임을 증명할 수 있는 경제적 근거를 포함해야 합니다.',
        'zh': '合作采购机构/组织',
    },
} as const;
